# Generated by Django 5.2.7 on 2025-12-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_poster_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='users',
            new_name='user',
        ),
    ]
